### ISSUE TITLE
Undeploying Embedded Mongo/Redis worker verticle

### ISSUE THREAD

**Issue by jchaganti** [aesteve/vertx-feeds#4]
Hi Arnaud,

First of all thanks for the reference implementation using vertx3. This has been immensely helpful.

I have a question regarding  Mongo/Redis worker verticle. Shouldn't these be undeployed? In MainVerticle, I found that you add deploymentIDs of FeedBroker and Webserver for undeployment, but do not do that for  the Mongo/Redis worker verticles that have been deployed. Am I right or am I missing something?

Thanks,
Janaki

**Comment by aesteve** [comment]
Sorry I've been away for such a long time.

You're absolutely right, it should be fixed now. Thanks for the issue ! :)
